# Generated by Django 3.0.5 on 2020-05-11 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bilet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_biletu', models.IntegerField()),
                ('czas_wjazdu', models.TimeField(verbose_name='%H:%M')),
                ('czas_wyjazdu', models.TimeField(verbose_name='%H:%M')),
                ('wykupiony_czas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cennik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oplata', models.DecimalField(decimal_places=2, max_digits=7)),
                ('czas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=200)),
                ('nazwisko', models.CharField(max_length=300)),
                ('nr_tel', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('liczba_stref', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RodzajParkingu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rodzaj', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TypPojazdu',
            fields=[
                ('typ', models.CharField(default='Brak', max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BiletDlugoterminowy',
            fields=[
                ('id_biletu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='parking_app.Bilet')),
            ],
        ),
        migrations.CreateModel(
            name='Strefa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
                ('pojemnosc', models.IntegerField()),
                ('liczba_wolnych_miejsc', models.IntegerField()),
                ('cennik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_app.Cennik')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_app.Parking')),
                ('typ_pojazdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_app.TypPojazdu')),
            ],
        ),
        migrations.CreateModel(
            name='Pojazd',
            fields=[
                ('nr_rejestracyjny', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_app.Klient')),
                ('typ_pojazdu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_app.TypPojazdu')),
            ],
        ),
        migrations.AddField(
            model_name='parking',
            name='rodzaj_parkingu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_app.RodzajParkingu'),
        ),
        migrations.CreateModel(
            name='MiejsceParkingowe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_miejsca', models.IntegerField()),
                ('strefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_app.Strefa')),
            ],
        ),
        migrations.AddField(
            model_name='cennik',
            name='rodzaj_parkingu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_app.RodzajParkingu'),
        ),
        migrations.AddField(
            model_name='bilet',
            name='strefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_app.Strefa'),
        ),
        migrations.CreateModel(
            name='Rezerwacja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_rezerwacji', models.IntegerField()),
                ('data_rozpoczecia', models.DateTimeField(verbose_name='%Y-%m-%d')),
                ('data_zakonczenia', models.DateTimeField(verbose_name='%Y-%m-%d')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_app.Klient')),
                ('miejsce_parkingowe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_app.MiejsceParkingowe')),
                ('bilet_dlugoterminowy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='parking_app.BiletDlugoterminowy')),
            ],
        ),
        migrations.AddField(
            model_name='biletdlugoterminowy',
            name='rezerwacja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_app.Rezerwacja'),
        ),
    ]
