# Generated by Django 3.0.3 on 2020-05-19 09:50

from django.db import migrations
import dane.initial_migration as im

class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(im.initial_migration)
    ]
