# Generated by Django 3.0.5 on 2020-06-18 17:05

from django.db import migrations
import dane.initial_migration as im


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(im.initial_migration)
    ]
