# Generated by Django 3.0.6 on 2020-05-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('wartosc', models.FloatField()),
                ('opis', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MetodaPlatnosci',
            fields=[
                ('rodzaj', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Znizka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('wartosc', models.FloatField()),
                ('opis', models.TextField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='parking',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parking_app.Parking'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rezerwacja',
            name='typ_pojazdu',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parking_app.TypPojazdu'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Oplata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('czas', models.DateTimeField(verbose_name='%Y-%m-%d')),
                ('kwota_podstawowa', models.FloatField()),
                ('kwota_ostateczna', models.FloatField()),
                ('status', models.CharField(max_length=1)),
                ('Bilet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_app.Bilet')),
                ('metoda_platnosci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_app.MetodaPlatnosci')),
                ('znizka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking_app.Znizka')),
            ],
        ),
        migrations.AddField(
            model_name='bilet',
            name='kara',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parking_app.Kara'),
            preserve_default=False,
        ),
    ]
