# Generated by Django 3.0.3 on 2020-05-18 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0002_auto_20200518_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biletdlugoterminowy',
            old_name='rezerwacja',
            new_name='rezerwacjad',
        ),
    ]
