# Generated by Django 3.0.3 on 2020-05-19 10:03

from django.db import migrations
import dane.tests_data_migration as tdm

class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0002_auto_20200519_0950'),
    ]

    operations = [
        migrations.RunPython(tdm.tests_data_migration)
    ]
