# Generated by Django 3.0.3 on 2020-05-19 10:31

from django.db import migrations
import dane.tests_data_migration as tdm

class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0003_auto_20200519_1003'),
    ]

    operations = [
        migrations.RunPython(tdm.update_strefa)
    ]
