# Generated by Django 3.0.3 on 2020-06-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0004_auto_20200519_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilet',
            name='czas_wyjazdu',
            field=models.DateTimeField(null=True, verbose_name='%Y-%m-%d %H:%M:%S'),
        ),
        migrations.AlterField(
            model_name='bilet',
            name='nr_biletu',
            field=models.IntegerField(blank=True),
        ),
    ]
