# Generated by Django 3.0.3 on 2020-05-19 07:52

from django.db import migrations
import dane.tests_data_migration as tdm

class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0008_auto_20200518_2040'),
    ]

    operations = [        
    ]
