# Generated by Django 3.0.3 on 2020-05-19 08:38


from django.db import migrations
import dane.tests_data_migration as tdm

class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0013_auto_20200519_0833'),
    ]

    operations = [
        migrations.RunPython(tdm.tests_data_migration)
    ]
