# Generated by Django 3.0.3 on 2020-05-19 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0014_auto_20200519_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezerwacja',
            name='parking',
        ),
        migrations.RemoveField(
            model_name='rezerwacja',
            name='typ_pojazdu',
        ),
        migrations.AlterField(
            model_name='biletdlugoterminowy',
            name='rezerwacjad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parking_app.Rezerwacja'),
        ),
        migrations.AlterField(
            model_name='rezerwacja',
            name='bilet_dlugoterminowy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='parking_app.BiletDlugoterminowy'),
        ),
    ]
