# Generated by Django 3.0.3 on 2020-05-19 09:04

from django.db import migrations
import dane.tests_data_migration as tdm

class Migration(migrations.Migration):

    dependencies = [
        ('parking_app', '0018_auto_20200519_0902'),
    ]

    operations = [
        migrations.RunPython(tdm.tests_data_migration)
    ]
